nameOverride: <+service.name>

podAnnotations:
  prometheus.io/scrape: 'true'
  prometheus.io/path: '/actuator/prometheus'
  prometheus.io/port: '8080'

env:
  config:
    JAVA_TOOL_OPTIONS: '-agentpath:/opt/harness-et/lib/libETAgent.so -XX:-UseTypeSpeculation -Xshare:off'


service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: "*"
      paths:
        - path: /anbu
          pathType: Exact

