nameOverride: <+service.name>

podAnnotations:
  prometheus.io/scrape: 'true'
  prometheus.io/path: '/actuator/prometheus'
  prometheus.io/port: '8080'

env:
  config:
    JAVA_TOOL_OPTIONS: '-agentpath:/opt/harness-et/lib/libETAgent.so -XX:-UseTypeSpeculation -Xshare:off'


ingress:
  enabled: true


service:
  type: ClusterIP
  port: 8080
