# harness.io/skip-file-for-deploy
apiVersion: v1
kind: Pod
metadata:
  name: manual-{{ include "fullstack-springboot-react.fullname" . }}
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
